import { Router, type IRouter } from "express";
import healthRouter from "./health";
import districtsRouter from "./districts";
import bargainingUnitsRouter from "./bargaining-units";
import employeesRouter from "./employees";
import salarySchedulesRouter from "./salary-schedules";
import hourlySchedulesRouter from "./hourly-schedules";
import scenariosRouter from "./scenarios";
import heatmapRouter from "./heatmap";
import dashboardRouter from "./dashboard";
import reportsRouter from "./reports";
import settingsRouter from "./settings";
import employeeGroupsRouter from "./employee-groups";
import compensationSchedulesRouter from "./compensation-schedules";
import stipendsRouter from "./stipends";
import flatRatesRouter from "./flat-rates";
import perDiemRouter from "./per-diem";
import hourlyCategoriesRouter from "./hourly-categories";
import salaryRangesRouter from "./salary-ranges";
import importGridRouter from "./import-grid";

const router: IRouter = Router();

router.use(healthRouter);
router.use(districtsRouter);
router.use(bargainingUnitsRouter);
router.use(employeesRouter);
router.use(salarySchedulesRouter);
router.use(hourlySchedulesRouter);
router.use(scenariosRouter);
router.use(heatmapRouter);
router.use(dashboardRouter);
router.use(reportsRouter);
router.use(settingsRouter);
router.use(employeeGroupsRouter);
router.use(compensationSchedulesRouter);
router.use(stipendsRouter);
router.use(flatRatesRouter);
router.use(perDiemRouter);
router.use(hourlyCategoriesRouter);
router.use(salaryRangesRouter);
router.use(importGridRouter);

export default router;
